/*
 Generated by typeshare 1.13.2
*/

export enum DDocumentType {
	File = "file",
	Terminal = "terminal",
	Settings = "settings",
}

export enum DDocumentStatus {
	New = "new",
	SavedToFs = "saved-to-fs",
	Modified = "modified",
}

export interface DDocumentRef {
	id: string;
	title: string;
	type: DDocumentType;
	file_path: string;
	status: DDocumentStatus;
}

export interface DTab {
	id: string;
	title: string;
	document_refs: DDocumentRef[];
	is_selected: boolean;
}

export interface DDocument {
	id: string;
	title: string;
	type: DDocumentType;
	file_path: string;
	buffer: string;
	status: DDocumentStatus;
}

export interface DWindowContent {
	documents: DDocument[];
}

export interface DFileTreeNode {
	id: string;
	name: string;
	is_expanded?: boolean;
	children: string[];
	level: number;
}

export enum DSidebarType {
	Tree = "tree",
	Tabs = "tabs",
}

export interface DInterface {
	is_overlay_active: boolean;
	sidebar: DSidebarType;
}

export interface DWindowState {
	id: string;
	tabs: DTab[];
	content: DWindowContent;
	file_path: string;
	file_list: DFileTreeNode[];
	ui: DInterface;
}

export interface DAppState {
	windows: Record<string, DWindowState>;
}

export enum DWindowStateScope {
	All = "All",
	FileList = "FileList",
	Tabs = "Tabs",
	Content = "Content",
}

export interface DWindowEventPayload {
	scope: DWindowStateScope;
}

export interface DWindowEventPayloadAll {
	scope: DWindowStateScope;
	window_state: DWindowState;
}

export interface DWindowEventPayloadContent {
	scope: DWindowStateScope;
	content: DWindowContent;
}

export interface DWindowEventPayloadFileList {
	scope: DWindowStateScope;
	file_list: DFileTreeNode[];
}

export interface DWindowEventPayloadTabs {
	scope: DWindowStateScope;
	tabs: DTab[];
}

